# Generated by Django 4.0.3 on 2022-05-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_alter_comment_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="recommend",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
